<?php if ($this->getCustomerId() && $this->getHost()): ?>
<!-- BEGIN: Analytics.Celebros.Search-->
<?php $protocol = ($this->getRequest()->isSecure())?'https':'http'; ?>
<script type="text/javascript">
require(["<?= $protocol ?>://<?= $this->getHost(); ?><?= $this->getJsPath(); ?>"], function() {
    anlxCallback = function() {
        var x = '';
    };
    CelebrosAnalytics.customerid = '<?= $this->getCustomerId(); ?>';
    CelebrosAnalytics.pagereferrer = '<?= $this->getPageReferrer(); ?>';
    CelebrosAnalytics.qwisersearchsessionid = '<?= $this->getQwiserSearchSessionId(); ?>';
    CelebrosAnalytics.websessionid = '<?= $this->getWebsessionId(); ?>';
<?php if ($qwisersearchloghandle = $this->getQwiserSearchLogHandle()): ?>
    CelebrosAnalytics.qwisersearchloghandle = '<?= $qwisersearchloghandle ?>';
<?php endif; ?>
    CelebrosAnalytics.issecured = <?= ($this->getRequest()->isSecure()) ? 'true' : 'false' ?>;
    CelebrosAnalytics.AI_LogSearchResult();
});
</script>
<!-- END: Analytics.Search -->
<?php endif; ?>