<?php if ($this->getCustomerId() && $this->getHost()): ?>
<!-- BEGIN: Analytics.Celebros.Product.Click-->
<?php $protocol = ($this->getRequest()->isSecure())?'https':'http'; ?>
<script type="text/javascript">
require(["<?php echo $protocol ?>://<?php echo $this->getHost(); ?><?php echo $this->getJsPath(); ?>"], function() {
    anlxCallback = function() {
        var x = '';
    };
    CelebrosAnalytics.customerid  = '<?php echo $this->getCustomerId(); ?>';
    CelebrosAnalytics.productsku  = '<?php echo $this->getProductSku(); ?>';
    CelebrosAnalytics.productname = '<?php echo $this->getProductName(); ?>';
    CelebrosAnalytics.productprice = '<?php echo $this->getProductPrice(); ?>';
    CelebrosAnalytics.websessionid = '<?php echo $this->getWebsessionId(); ?>';
    CelebrosAnalytics.AI_LogProduct();
});
</script>
<!-- END: Analytics.Celebros.Product.Click-->
<?php endif?>