<?php if ($this->getCustomerId() && $this->getHost()): ?>
<!-- BEGIN: Analytics.Celebros.Search-->
<?php $protocol = ($this->getRequest()->isSecure())?'https':'http'; ?>
<script type="text/javascript">
require(["<?php echo $protocol ?>://<?php echo $this->getHost(); ?><?php echo $this->getJsPath(); ?>"], function() {
    anlxCallback = function() {
        var x = '';
    };
    CelebrosAnalytics.customerid = '<?php echo $this->getCustomerId(); ?>';
    CelebrosAnalytics.pagereferrer = '<?php echo $this->getPageReferrer(); ?>';
    CelebrosAnalytics.qwisersearchsessionid = '<?php echo $this->getQwiserSearchSessionId(); ?>';
    CelebrosAnalytics.websessionid = '<?php echo $this->getWebsessionId(); ?>';
<?php if ($qwisersearchloghandle = $this->getQwiserSearchLogHandle()): ?>
    CelebrosAnalytics.qwisersearchloghandle = '<?php echo $qwisersearchloghandle ?>';
<?php endif; ?>
    CelebrosAnalytics.issecured = <?php echo ($this->getRequest()->isSecure()) ? 'true' : 'false' ?>;
    CelebrosAnalytics.AI_LogSearchResult();
});
</script>
<!-- END: Analytics.Search -->
<?php endif; ?>