<?php if ($this->getCustomerId() && $this->getHost()): ?>
<!-- BEGIN: Analytics.Celebros.Product.Click-->
<?php $protocol = ($this->getRequest()->isSecure()) ? 'https' : 'http'; ?>
<script type="text/javascript">
require(["<?= $protocol ?>://<?= $this->getHost(); ?><?= $this->getJsPath(); ?>"], function() {
    anlxCallback = function() {
        var x = '';
    };
    CelebrosAnalytics.customerid  = '<?= $this->getCustomerId(); ?>';
    CelebrosAnalytics.productsku  = '<?= $this->getProductSku(); ?>';
    CelebrosAnalytics.productname = '<?= $this->getProductName(); ?>';
    CelebrosAnalytics.productprice = '<?= $this->getProductPrice(); ?>';
    CelebrosAnalytics.websessionid = '<?= $this->getWebsessionId(); ?>';
    CelebrosAnalytics.issecured = <?php echo ($this->getRequest()->isSecure()) ? 'true' : 'false' ?>;
    CelebrosAnalytics.AI_LogProduct();
});
</script>
<!-- END: Analytics.Celebros.Product.Click-->
<?php endif?>