<?php $helper = $this->helper('\Celebros\ConversionPro\Helper\Data') ?>
<div class="swatch-attribute swatch-layered <?php echo $filterType ?>">
    <div class="swatch-attribute-options clearfix">
    <?php foreach ($filterItems as $key => $filterItem): ?>
    <?php if ($filterItem->getCount() > 0): ?>
        <?php if ($filterItem->getSwatchImage()): ?>
        <?php $style = $filterItem->getSwatchImage() != '#' ? "background-image: url('" . $filterItem->getSwatchImage() . "');" : "background: " . $filterItem->getLabel() . ";"; ?>
        <a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
            <div class="swatch-option image<?php if ($filterItem->isSelected()): ?> checked<?php endif; ?>" style="<?php echo $style ?>"></div>
        </a>
        <?php endif; ?>
    <?php endif; ?>
    <?php endforeach ?>
    </div>
</div>