<?php $helper = $this->helper('\Celebros\ConversionPro\Helper\Data') ?>
<div class="swatch-attribute swatch-layered <?php echo $filterType ?>">
    <div class="swatch-attribute-options clearfix">
    <?php foreach ($filterItems as $key => $filterItem): ?>
    <?php if ($filterItem->getCount() > 0): ?>
        <?php if ($filterItem->getSwatchImage()): ?>
        <a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
            <div class="swatch-option image<?php if ($filterItem->isSelected()): ?> checked<?php endif; ?>" style="background-image: url('<?php echo $filterItem->getSwatchImage() ?>')"></div>
        </a>
        <?php endif; ?>
    <?php endif; ?>
    <?php endforeach ?>
    </div>
</div>