<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Layer\Filter\Renderer
 */
?>
<?php $helper = $this->helper('\Celebros\ConversionPro\Helper\Data') ?>
<style>
.item.hided {
    display: none;
}
.item.more-button,
.item.less-button {
    cursor: pointer;
}
.celebros-price-min,
.celebros-price-max {
    width: 25% !important;
}
</style>
<?php if ($filterType != 'price' || in_array('default', $helper->getFilterType())): ?>
<ol class="items">
    <?php foreach ($filterItems as $key => $filterItem): ?>
    <?php if ($helper->isCollapsed() && ($helper->collapseQty() <= $key)): ?>
    <li class="item<?php if ($key >= (int)$helper->collapseQty()) echo ' hided' ?><?php if ($filterItem->isSelected()): ?> selected<?php endif; ?>">
    <?php else: ?>
    <li class="item<?php if ($filterItem->isSelected()): ?> selected<?php endif; ?>">
    <?php endif; ?>
    <?php if ($filterItem->getCount() > 0): ?>
        <?php if ($helper->isMultiselectEnabled()): ?>
        <input type="checkbox" data-href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>" onclick="convpro.clickCheckbox(this)"<?php if ($filterItem->isSelected()): ?> checked="checked"<?php endif; ?>>
        <?php endif; ?>
        <a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>" onclick="convpro.clickHLink(this)">
            <?php echo $filterItem->getLabel() ?>
            <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
            <span class="count"><?php echo $filterItem->getCount()?><span class="filter-count-label">
            <?php if ($filterItem->getCount() == 1):?>
                <?php echo __('item') ?>
            <?php else:?>
                <?php echo __('items') ?>
            <?php endif;?>
            </span></span>
            <?php endif; ?>
        </a>
        <?php else:?>
        <?php echo $filterItem->getLabel() ?>
        <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
        <span class="count">(<?php echo $filterItem->getCount()?>)<span class="filter-count-label">
            <?php if ($filterItem->getCount() == 1):?>
                <?php echo __('item')?><?php else:?><?php echo __('items') ?>
            <?php endif;?>
        </span></span>
        <?php endif; ?>
    <?php endif; ?>
    </li>
    <?php endforeach ?>
    <?php if ($helper->isCollapsed() && ($helper->collapseQty() < sizeof($filterItems))): ?>
    <li class="item more-button" data-collapse="more" onclick="convpro.collapse(this, true)">+ <?php echo __('More') ?></li>
    <li class="item less-button hided" data-collapse="less" onclick="convpro.collapse(this, false)">- <?php echo __('Less') ?></li>
    <?php endif; ?>
</ol>
<?php endif; ?>
<?php if ($filterType == 'price' && in_array('inputs', $helper->getFilterType())): ?>
    <?php $sHelper = $this->helper('\Celebros\ConversionPro\Helper\Search'); ?>
    <?php if ($sHelper->getMinMaxPrices('min')): ?>
    <input onchange="convpro.minMaxCheck(this)" data-min-price="<?php echo $sHelper->getMinMaxPrices('min') ?>" id="input-price-min" placeholder="<?php echo $sHelper->getMinMaxPrices('min') ?>" class="input-text celebros-price-min" maxlength="4" type="number"><span> <?php echo __('to') ?> </span>
    <input onchange="convpro.minMaxCheck(this)" data-max-price="<?php echo $sHelper->getMinMaxPrices('max') ?>" id="input-price-max" placeholder="<?php echo $sHelper->getMinMaxPrices('max') ?>" class="input-text celebros-price-max" maxlength="4" type="number">
    <button id="price-apply-button" data-url="<?php echo $helper->getPriceUrlTemplate() ?>" class="action search" type="submit" title="<?php echo __('Search') ?>" onclick="convpro.applyPrice(this)" disabled>
        <span><?php echo __('Filter') ?></span>
    </button>
    <?php endif; ?>
<?php endif; ?>