<?php $helper = $this->helper('\Celebros\ConversionPro\Helper\Data'); ?>
<?php $sHelper = $this->helper('\Celebros\ConversionPro\Helper\Search'); ?>
<script type="text/x-magento-init">
{
    "*": {
        "conversionpro/filters" : {
            "filters": {
                "multiselect" : {
                    "status": <?php echo $helper->toJsBool($helper->isMultiselectEnabled()) ?>,
                    "selectors": {
                        "checkboxSelector": ".filter-options-content .item input[type='checkbox']",
                        "hlinkSelector": ".filter-options-content .item a"
                    },
                    "options": {}
                },
                "collapse" : {
                    "status": <?php echo $helper->toJsBool($helper->isCollapsed()) ?>,
                    "selectors": {
                        "mainSelector": ".items"
                    },
                    "options": {
                        "collapseQty" : <?php echo (int) $helper->collapseQty() ?>
                    }
                },
                "search": {
                    "status" : <?php echo $helper->toJsBool($helper->isFilterSearchEnabled()) ?>,
                    "selectors": {
                        "filtersList": "#narrow-by-list .filter-options-content"
                    },
                    "options": {
                        "filterSearchQty" : <?php echo (int) $helper->getMinQtyForFilterSearch() ?>
                    }
                },
                "price-inputs": {
                    "status" : <?php echo $helper->toJsBool($helper->isPriceInputs()) ?>,
                    "selectors": {},
                    "options": {}
                },
                "price-slider": {
                    "status" : <?php echo $helper->toJsBool($helper->isPriceSlider()) ?>,
                    "selectors": {
                        "sliderElement": "#celebros-price-slider",
                        "sliderAmount": "#celebros-price-slider-amount"
                    },
                    "options": {
                        "minPrice": <?php echo $sHelper->getMinMaxPrices('min') ?>,
                        "maxPrice": <?php echo $sHelper->getMinMaxPrices('max') ?>,
                        "currentMinPrice": <?php echo $sHelper->getMinMaxPrices('min') ?>,
                        "currentMaxPrice": <?php echo $sHelper->getMinMaxPrices('max') ?>,
                        "amountHtml": "{min_val} - {max_val}"
                    }
                }
            }
        }
    }
}
</script>